# Generated by Django 5.0.1 on 2024-10-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millar', models.IntegerField()),
                ('posicion_millar', models.IntegerField()),
                ('numero_socio', models.IntegerField()),
                ('nombre_y_apellidos', models.CharField(max_length=100)),
            ],
        ),
    ]
