# Generated by Django 5.0.1 on 2024-11-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVParticipantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csvs/')),
            ],
            options={
                'verbose_name': 'CSV de participantes',
                'verbose_name_plural': 'CSVs de participantes',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millar', models.IntegerField()),
                ('posicion_millar', models.IntegerField()),
                ('numero_socio', models.IntegerField()),
                ('nombre_y_apellidos', models.CharField(max_length=100)),  
                ('ganador', models.BooleanField(blank=True, null=True)),   
                ('ganador_primera_fase', models.BooleanField(blank=True, null=True)),
                ('ganador_segunda_fase', models.BooleanField(blank=True, null=True)),
                ('ganador_tercera_fase', models.BooleanField(blank=True, null=True)),
                ('reserva_tercera_fase', models.BooleanField(blank=True, default=False)),
                ('millar_ganador', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['millar', 'posicion_millar', 'numero_socio', 'nombre_y_apellidos'],
            },
        ),
    ]