# Generated by Django 5.0.1 on 2024-10-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_csvparticipantes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvparticipantes',
            options={'verbose_name': 'CSV de participantes', 'verbose_name_plural': 'CSVs de participantes'},
        ),
        migrations.AlterModelOptions(
            name='participante',
            options={'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AddField(
            model_name='participante',
            name='ganador',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
