# Generated by Django 5.0.1 on 2024-10-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_csvparticipantes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participante',
            options={'ordering': ['millar', 'posicion_millar', 'numero_socio', 'nombre_y_apellidos'], 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
    ]
