# Generated by Django 5.0.1 on 2024-10-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_participante_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='ganador_primera_fase',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='ganador_segunda_fase',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
