# Generated by Django 5.0.1 on 2024-10-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_participante_ganador_primera_fase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='ganador_tercera_fase',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
