# Generated by Django 5.0.1 on 2024-10-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_participante_ganador_tercera_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='reserva_tercera_fase',
            field=models.BooleanField(default=False),
        ),
    ]
