# Generated by Django 5.0.1 on 2024-11-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_participante_reserva_tercera_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='tercera_fase_millar_ganador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='reserva_tercera_fase',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
